// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class Bread
	{

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("trainpoint")]
		public int Trainpoint { get; set; }

		[JsonProperty("sellprice")]
		public int Sellprice { get; set; }

		[JsonProperty("grade")]
		public int Grade { get; set; }

		[JsonProperty("class")]
		public string[] Class { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("texture")]
		public string Texture { get; set; }

		[JsonProperty("critprob")]
		public double Critprob { get; set; }
	}

	public class BreadBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("bread")]
		public Bread[] Bread { get; set; }
	}

}
