// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{
    public class CharacterClass
    {
        [JsonProperty("presentflagimg")]
        public string Presentflagimg { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("combatdistance")]
        public double Combatdistance { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("range")]
        public double Range { get; set; }

        [JsonProperty("categoryid")]
        public string Categoryid { get; set; }

        [JsonProperty("desc")]
        public string Desc { get; set; }
    }

    public class CharacterClassBase
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("characterclass")]
        public CharacterClass[] CharacterClass { get; set; }
    }
}
