// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

    public class Part
    {
        [JsonProperty("node")]
        public string Node { get; set; }

        [JsonProperty("prefab")]
        public string Prefab { get; set; }

        [JsonProperty("sync")]
        public bool Sync { get; set; }

        [JsonProperty("texture")]
        public string Texture { get; set; }

        [JsonProperty("dependency")]
        public bool Dependency { get; set; }

        [JsonProperty("offset")]
        public double[] Offset { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public class Character
    {

        [JsonProperty("classid")]
        public string Classid { get; set; }

        [JsonProperty("rarity")]
        public string Rarity { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("bodyheight")]
        public double Bodyheight { get; set; }

        [JsonProperty("upgradetargethero")]
        public string Upgradetargethero { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("ui_hp_offset_y")]
        public double UiHpOffsetY { get; set; }

        [JsonProperty("parts")]
        public Part[] Parts { get; set; }

        [JsonProperty("face_tex")]
        public string FaceTex { get; set; }

        [JsonProperty("howtoget")]
        public string[] Howtoget { get; set; }

        [JsonProperty("bodywidth")]
        public double Bodywidth { get; set; }

        [JsonProperty("job")]
        public string Job { get; set; }

        [JsonProperty("drawmode")]
        public string Drawmode { get; set; }

        [JsonProperty("overhead")]
        public double Overhead { get; set; }

        [JsonProperty("skin_tex")]
        public string SkinTex { get; set; }

        [JsonProperty("deadsound")]
        public string Deadsound { get; set; }

        [JsonProperty("default_stat_id")]
        public string DefaultStatId { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("desc")]
        public string Desc { get; set; }
    }

    public class CharacterBase
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("character_visual")]
        public Character[] Character { get; set; }
    }

}
