// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

    public class SkillCondition
    {
        [JsonProperty("RANGED_FOE")]
        public string RANGEDFOE { get; set; }

        [JsonProperty("AB_HERO_SKILL")]
        public string ABHEROSKILL { get; set; }

        [JsonProperty("PASSIVE")]
        public string PASSIVE { get; set; }

        [JsonProperty("FIX_BALL")]
        public string FIXBALL { get; set; }

        [JsonProperty("ROUST")]
        public string ROUST { get; set; }
    }
    public class CharacterStat
    {

        [JsonProperty("classid")]
        public string Classid { get; set; }

        [JsonProperty("resist")]
        public double Resist { get; set; }

        [JsonProperty("skillconditionjson")]
        public SkillCondition[] Skillconditionjson { get; set; }

        [JsonProperty("growthresist")]
        public double Growthresist { get; set; }

        [JsonProperty("critpower")]
        public double Critpower { get; set; }

        [JsonProperty("grade")]
        public int Grade { get; set; }

        [JsonProperty("pattern")]
        public string Pattern { get; set; }

        [JsonProperty("growthhp")]
        public double Growthhp { get; set; }

        [JsonProperty("knockback_resistancerate")]
        public double KnockbackResistancerate { get; set; }

        [JsonProperty("initialattdmg")]
        public double Initialattdmg { get; set; }

        [JsonProperty("initialhp")]
        public double Initialhp { get; set; }

        [JsonProperty("passiveslot")]
        public int Passiveslot { get; set; }

        [JsonProperty("growthdefense")]
        public double Growthdefense { get; set; }

        [JsonProperty("defense")]
        public double Defense { get; set; }

        [JsonProperty("growthattdmg")]
        public double Growthattdmg { get; set; }

        [JsonProperty("vamp")]
        public double Vamp { get; set; }

        [JsonProperty("id")]
        public string ID { get; set; }

        [JsonProperty("critprob")]
        public double Critprob { get; set; }
    }

    public class CharacterStatBase
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("character_stat")]
        public CharacterStat[] CharacterStat { get; set; }
    }

}
