// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class Talkjson
	{

		[JsonProperty("sisdog_action")]
		public string SisdogAction { get; set; }

		[JsonProperty("sisdog_texture")]
		public string SisdogTexture { get; set; }

		[JsonProperty("sisdog_dest")]
		public string SisdogDest { get; set; }

		[JsonProperty("talker_name")]
		public string TalkerName { get; set; }

		[JsonProperty("talker_desc")]
		public string TalkerDesc { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("sisforest_action")]
		public string SisforestAction { get; set; }

		[JsonProperty("sisforest_texture")]
		public string SisforestTexture { get; set; }

		[JsonProperty("sisforest_dest")]
		public string SisforestDest { get; set; }

		[JsonProperty("sisdesert_texture")]
		public string SisdesertTexture { get; set; }

		[JsonProperty("sisdesert_action")]
		public string SisdesertAction { get; set; }

		[JsonProperty("sisdesert_dest")]
		public string SisdesertDest { get; set; }

		[JsonProperty("siskraken_texture")]
		public string SiskrakenTexture { get; set; }

		[JsonProperty("siskraken_action")]
		public string SiskrakenAction { get; set; }

		[JsonProperty("siskraken_dest")]
		public string SiskrakenDest { get; set; }

		[JsonProperty("sisdragon_texture")]
		public string SisdragonTexture { get; set; }

		[JsonProperty("sisdragon_action")]
		public string SisdragonAction { get; set; }

		[JsonProperty("sisdragon_dest")]
		public string SisdragonDest { get; set; }

		[JsonProperty("dione_dest")]
		public string DioneDest { get; set; }

		[JsonProperty("dione_action")]
		public string DioneAction { get; set; }

		[JsonProperty("dione_texture")]
		public string DioneTexture { get; set; }

		[JsonProperty("brigit_action")]
		public string BrigitAction { get; set; }

		[JsonProperty("brigit_texture")]
		public string BrigitTexture { get; set; }

		[JsonProperty("brigit_dest")]
		public string BrigitDest { get; set; }

		[JsonProperty("fugus_dest")]
		public string FugusDest { get; set; }

		[JsonProperty("fugus_texture")]
		public string FugusTexture { get; set; }

		[JsonProperty("fugus_action")]
		public string FugusAction { get; set; }

		[JsonProperty("helled_dest")]
		public string HelledDest { get; set; }

		[JsonProperty("helled_texture")]
		public string HelledTexture { get; set; }

		[JsonProperty("helled_action")]
		public string HelledAction { get; set; }

		[JsonProperty("chocolat_action")]
		public string ChocolatAction { get; set; }

		[JsonProperty("chocolat_texture")]
		public string ChocolatTexture { get; set; }

		[JsonProperty("chocolat_dest")]
		public string ChocolatDest { get; set; }

		[JsonProperty("popo_dest")]
		public string PopoDest { get; set; }

		[JsonProperty("popo_texture")]
		public string PopoTexture { get; set; }

		[JsonProperty("popo_action")]
		public string PopoAction { get; set; }

		[JsonProperty("rednas_action")]
		public string RednasAction { get; set; }

		[JsonProperty("rednas_dest")]
		public string RednasDest { get; set; }

		[JsonProperty("rednas_texture")]
		public string RednasTexture { get; set; }

		[JsonProperty("leon_action")]
		public string LeonAction { get; set; }

		[JsonProperty("leon_dest")]
		public string LeonDest { get; set; }

		[JsonProperty("leon_texture")]
		public string LeonTexture { get; set; }

		[JsonProperty("gon_action")]
		public string GonAction { get; set; }

		[JsonProperty("gon_dest")]
		public string GonDest { get; set; }

		[JsonProperty("gon_texture")]
		public string GonTexture { get; set; }

		[JsonProperty("dart_action")]
		public string DartAction { get; set; }

		[JsonProperty("dart_texture")]
		public string DartTexture { get; set; }

		[JsonProperty("dart_dest")]
		public string DartDest { get; set; }

		[JsonProperty("sigruna_dest")]
		public string SigrunaDest { get; set; }

		[JsonProperty("sigruna_texture")]
		public string SigrunaTexture { get; set; }

		[JsonProperty("sigruna_action")]
		public string SigrunaAction { get; set; }

		[JsonProperty("maria_texture")]
		public string MariaTexture { get; set; }

		[JsonProperty("maria_dest")]
		public string MariaDest { get; set; }

		[JsonProperty("maria_action")]
		public string MariaAction { get; set; }

		[JsonProperty("doro_dest")]
		public string DoroDest { get; set; }

		[JsonProperty("doro_texture")]
		public string DoroTexture { get; set; }

		[JsonProperty("doro_action")]
		public string DoroAction { get; set; }

		[JsonProperty("silunis_dest")]
		public string SilunisDest { get; set; }

		[JsonProperty("silunis_texture")]
		public string SilunisTexture { get; set; }

		[JsonProperty("silunis_action")]
		public string SilunisAction { get; set; }

		[JsonProperty("darksisdog_dest")]
		public string DarksisdogDest { get; set; }

		[JsonProperty("darksisdog_action")]
		public string DarksisdogAction { get; set; }

		[JsonProperty("darksisdog_texture")]
		public string DarksisdogTexture { get; set; }

		[JsonProperty("nemesis_texture")]
		public string NemesisTexture { get; set; }

		[JsonProperty("nemesis_action")]
		public string NemesisAction { get; set; }

		[JsonProperty("nemesis_dest")]
		public string NemesisDest { get; set; }

		[JsonProperty("ssisdragon_action")]
		public string SsisdragonAction { get; set; }

		[JsonProperty("archon_dest")]
		public string ArchonDest { get; set; }

		[JsonProperty("archon_texture")]
		public string ArchonTexture { get; set; }

		[JsonProperty("archon_action")]
		public string ArchonAction { get; set; }

		[JsonProperty("soltar_texture")]
		public string SoltarTexture { get; set; }

		[JsonProperty("soltar_dest")]
		public string SoltarDest { get; set; }

		[JsonProperty("soltar_action")]
		public string SoltarAction { get; set; }
	}

	public class Dialogue
	{

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("talkjson")]
		public Talkjson[] Talkjson { get; set; }

		[JsonProperty("subtype")]
		public string Subtype { get; set; }

		[JsonProperty("type")]
		public string Type { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("titlename")]
		public string Titlename { get; set; }
	}

	public class DialogueBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("dialogues")]
		public Dialogue[] Dialogues { get; set; }
	}

}
