// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class SisSkillHandler
	{

		[JsonProperty("stat")]
		public string Stat { get; set; }

		[JsonProperty("target")]
		public string Target { get; set; }

		[JsonProperty("value")]
		public double Value { get; set; }

		[JsonProperty("vfx")]
		public string Vfx { get; set; }

		[JsonProperty("duration")]
		public double Duration { get; set; }

		[JsonProperty("ResistCleanse")]
		public bool ResistCleanse { get; set; }

		[JsonProperty("condition")]
		public string Condition { get; set; }

		[JsonProperty("value.target")]
		public string ValueTarget { get; set; }
	}

	public class SkillhandlerJson2
	{

		[JsonProperty("sisSkillHandlers")]
		public SisSkillHandler[] SisSkillHandlers { get; set; }
	}

	public class Sister
	{

		[JsonProperty("bgduration")]
		public double Bgduration { get; set; }

		[JsonProperty("dsp_tex")]
		public string DspTex { get; set; }

		[JsonProperty("skin_tex")]
		public string SkinTex { get; set; }

		[JsonProperty("bgeffect")]
		public string Bgeffect { get; set; }

		[JsonProperty("skillhandler_json")]
		public SkillhandlerJson2 SkillhandlerJson { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("init_vfx")]
		public string InitVfx { get; set; }

		[JsonProperty("skilldesc")]
		public string Skilldesc { get; set; }

		[JsonProperty("skillname")]
		public string Skillname { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("priority")]
		public int Priority { get; set; }

		[JsonProperty("ceremony_vfx")]
		public object CeremonyVfx { get; set; }
	}

	public class GoddessBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("sister")]
		public Sister[] Sister { get; set; }
	}

}
