// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{
	public class PvpRoundreward
	{
		[JsonProperty("streak")]
		public int Streak { get; set; }

		[JsonProperty("heartreward")]
		public int Heartreward { get; set; }

		[JsonProperty("ratingvariation")]
		public int Ratingvariation { get; set; }

		[JsonProperty("leagueid")]
		public string Leagueid { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("honorreward")]
		public int Honorreward { get; set; }

		[JsonProperty("ratingdecrease")]
		public int Ratingdecrease { get; set; }
	}

	public class PvPRewardBase
	{
		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("pvp_roundreward")]
		public PvpRoundreward[] PvpRoundreward { get; set; }
	}

}
