// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class PvpWeekreward
	{

		[JsonProperty("ratioupper")]
		public double Ratioupper { get; set; }

		[JsonProperty("jewelreward")]
		public int Jewelreward { get; set; }

		[JsonProperty("leagueid")]
		public string Leagueid { get; set; }

		[JsonProperty("ratiolower")]
		public double Ratiolower { get; set; }

		[JsonProperty("type")]
		public string Type { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }
	}

	public class PvPWeekRewardBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("pvp_weekreward")]
		public PvpWeekreward[] PvpWeekreward { get; set; }
	}

}
