// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{
	public class BossInfo
	{
		[JsonProperty("level")]
		public int level { get; set; }
		[JsonProperty("desc")]
		public string desc { get; set; }
		[JsonProperty("icon")]
		public string icon { get; set; }
	}

	public class Props
	{

		[JsonProperty("addState")]
		public object AddState { get; set; }

		[JsonProperty("projectile")]
		public string Projectile { get; set; }

		[JsonProperty("sfx")]
		public object Sfx { get; set; }

		[JsonProperty("pos.unit.front.y")]
		public object PosUnitFrontY { get; set; }

		[JsonProperty("pos.unit.front.x")]
		public object PosUnitFrontX { get; set; }

		[JsonProperty("vfx")]
		public object Vfx { get; set; }

		[JsonProperty("lifetime")]
		public object Lifetime { get; set; }

		[JsonProperty("damage.value")]
		public object DamageValue { get; set; }

		[JsonProperty("push")]
		public double? Push { get; set; }

		[JsonProperty("fire.speed")]
		public object FireSpeed { get; set; }

		[JsonProperty("fly")]
		public double? Fly { get; set; }

		[JsonProperty("CRIT_PROB")]
		public double? CRITPROB { get; set; }

		[JsonProperty("force.ground")]
		public bool? ForceGround { get; set; }

		[JsonProperty("move.speed")]
		public double? MoveSpeed { get; set; }

		[JsonProperty("shaking")]
		public bool? Shaking { get; set; }

		[JsonProperty("move.speed.prjc")]
		public int? MoveSpeedPrjc { get; set; }

		[JsonProperty("CRIT_DMG")]
		public double? CRITDMG { get; set; }

		[JsonProperty("vamp")]
		public double? Vamp { get; set; }

		[JsonProperty("VAMP")]
		public double? VAMP { get; set; }

		[JsonProperty("pull")]
		public double? Pull { get; set; }

		[JsonProperty("repeat.interval")]
		public double? RepeatInterval { get; set; }

		[JsonProperty("repeat.count")]
		public object RepeatCount { get; set; }

		[JsonProperty("hit.effect")]
		public string HitEffect { get; set; }

		[JsonProperty("heal.type")]
		public string HealType { get; set; }

		[JsonProperty("pos.target.front.x")]
		public object PosTargetFrontX { get; set; }

		[JsonProperty("pos.target.front.y")]
		public double? PosTargetFrontY { get; set; }

		[JsonProperty("heal.value")]
		public object HealValue { get; set; }

		[JsonProperty("target.iff")]
		public string TargetIff { get; set; }

		[JsonProperty("target.method")]
		public string TargetMethod { get; set; }

		[JsonProperty("damage.type")]
		public string DamageType { get; set; }

		[JsonProperty("on.destroy")]
		public string[] OnDestroy { get; set; }

		[JsonProperty("stun")]
		public double? Stun { get; set; }

		[JsonProperty("fire.degree")]
		public object FireDegree { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }

		[JsonProperty("pos.reach.degree")]
		public object PosReachDegree { get; set; }

		[JsonProperty("reach.offset.x")]
		public object ReachOffsetX { get; set; }

		[JsonProperty("reach.pos")]
		public string ReachPos { get; set; }

		[JsonProperty("on.hit.prob")]
		public double? OnHitProb { get; set; }

		[JsonProperty("pos.param")]
		public string PosParam { get; set; }

		[JsonProperty("poolNum")]
		public int? PoolNum { get; set; }

		[JsonProperty("pos.jump.x")]
		public int? PosJumpX { get; set; }

		[JsonProperty("pos.jump.y")]
		public double? PosJumpY { get; set; }

		[JsonProperty("offset.x")]
		public object OffsetX { get; set; }

		[JsonProperty("offset.y")]
		public double? OffsetY { get; set; }

		[JsonProperty("pullNum")]
		public int? PullNum { get; set; }

		[JsonProperty("PENETRATE_RST")]
		public int? PENETRATERST { get; set; }

		[JsonProperty("PENETRATE_DEF")]
		public int? PENETRATEDEF { get; set; }
	}

	public class SkillSecondHandler
	{

		[JsonProperty("codehandler")]
		public string Codehandler { get; set; }

		[JsonProperty("run.timing")]
		public double RunTiming { get; set; }

		[JsonProperty("props")]
		public Props Props { get; set; }

		[JsonProperty("run.ani_event")]
		public int[] RunAniEvent { get; set; }

		[JsonProperty("label")]
		public string Label { get; set; }

		[JsonProperty("run.wait")]
		public string RunWait { get; set; }
	}

	public class Props2
	{

		[JsonProperty("addState")]
		public object AddState { get; set; }

		[JsonProperty("projectile")]
		public string Projectile { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }

		[JsonProperty("damage.value")]
		public object DamageValue { get; set; }

		[JsonProperty("pos.unit.front.y")]
		public object PosUnitFrontY { get; set; }

		[JsonProperty("pos.unit.front.x")]
		public object PosUnitFrontX { get; set; }

		[JsonProperty("lifetime")]
		public object Lifetime { get; set; }

		[JsonProperty("target.method")]
		public string TargetMethod { get; set; }

		[JsonProperty("offset.x")]
		public object OffsetX { get; set; }

		[JsonProperty("pos.param")]
		public string PosParam { get; set; }

		[JsonProperty("repeat.count")]
		public object RepeatCount { get; set; }

		[JsonProperty("repeat.interval")]
		public double? RepeatInterval { get; set; }

		[JsonProperty("fire.speed")]
		public object FireSpeed { get; set; }

		[JsonProperty("sfx")]
		public object Sfx { get; set; }

		[JsonProperty("vfx")]
		public object Vfx { get; set; }

		[JsonProperty("push")]
		public double? Push { get; set; }

		[JsonProperty("fly")]
		public double? Fly { get; set; }

		[JsonProperty("CRIT_PROB")]
		public double? CRITPROB { get; set; }

		[JsonProperty("force.ground")]
		public bool? ForceGround { get; set; }

		[JsonProperty("move.speed")]
		public double? MoveSpeed { get; set; }

		[JsonProperty("shaking")]
		public bool? Shaking { get; set; }

		[JsonProperty("duration")]
		public double? Duration { get; set; }

		[JsonProperty("move.speed.prjc")]
		public int? MoveSpeedPrjc { get; set; }

		[JsonProperty("CRIT_DMG")]
		public double? CRITDMG { get; set; }

		[JsonProperty("vamp")]
		public double? Vamp { get; set; }

		[JsonProperty("VAMP")]
		public double? VAMP { get; set; }

		[JsonProperty("pull")]
		public double? Pull { get; set; }

		[JsonProperty("pos.target.front.x")]
		public object PosTargetFrontX { get; set; }

		[JsonProperty("pos.target.front.y")]
		public object PosTargetFrontY { get; set; }

		[JsonProperty("PENETRATE_DEF")]
		public int? PENETRATEDEF { get; set; }

		[JsonProperty("stun")]
		public double? Stun { get; set; }

		[JsonProperty("damage.type")]
		public string DamageType { get; set; }

		[JsonProperty("hit.effect")]
		public string HitEffect { get; set; }

		[JsonProperty("heal.type")]
		public string HealType { get; set; }

		[JsonProperty("heal.value")]
		public object HealValue { get; set; }

		[JsonProperty("target.iff")]
		public string TargetIff { get; set; }

		[JsonProperty("on.destroy")]
		public string[] OnDestroy { get; set; }

		[JsonProperty("pos.jump.x")]
		public double? PosJumpX { get; set; }

		[JsonProperty("pos.jump.y")]
		public double? PosJumpY { get; set; }

		[JsonProperty("fire.degree")]
		public object FireDegree { get; set; }

		[JsonProperty("pos.reach.degree")]
		public object PosReachDegree { get; set; }

		[JsonProperty("reach.offset.x")]
		public object ReachOffsetX { get; set; }

		[JsonProperty("reach.pos")]
		public string ReachPos { get; set; }

		[JsonProperty("on.hit.prob")]
		public double? OnHitProb { get; set; }

		[JsonProperty("poolNum")]
		public int? PoolNum { get; set; }

		[JsonProperty("offset.y")]
		public double? OffsetY { get; set; }

		[JsonProperty("PENETRATE_RST")]
		public int? PENETRATERST { get; set; }

		[JsonProperty("pullNum")]
		public int? PullNum { get; set; }
	}

	public class Vfx
	{

		[JsonProperty("prefab")]
		public string Prefab { get; set; }

		[JsonProperty("attach")]
		public bool Attach { get; set; }

		[JsonProperty("offset.x")]
		public int OffsetX { get; set; }

		[JsonProperty("offset.y")]
		public int OffsetY { get; set; }

		[JsonProperty("lifetime")]
		public int Lifetime { get; set; }
	}

	public class Sfx
	{

		[JsonProperty("key")]
		public string Key { get; set; }
	}

	public class SkillHandler
	{

		[JsonProperty("codehandler")]
		public string Codehandler { get; set; }

		[JsonProperty("run.timing")]
		public double RunTiming { get; set; }

		[JsonProperty("props")]
		public Props2 Props { get; set; }

		[JsonProperty("run.ani_event")]
		public int[] RunAniEvent { get; set; }

		[JsonProperty("label")]
		public string Label { get; set; }

		[JsonProperty("vfx")]
		public Vfx Vfx { get; set; }

		[JsonProperty("sfx")]
		public Sfx Sfx { get; set; }

		[JsonProperty("run.wait")]
		public string RunWait { get; set; }

		[JsonProperty("lifetime")]
		public int? Lifetime { get; set; }
	}

	public class Props3
	{

		[JsonProperty("fire.speed")]
		public object FireSpeed { get; set; }

		[JsonProperty("damage.value")]
		public object DamageValue { get; set; }

		[JsonProperty("pos.unit.front.x")]
		public object PosUnitFrontX { get; set; }

		[JsonProperty("projectile")]
		public string Projectile { get; set; }

		[JsonProperty("push")]
		public double Push { get; set; }

		[JsonProperty("lifetime")]
		public double Lifetime { get; set; }

		[JsonProperty("pos.unit.front.y")]
		public object PosUnitFrontY { get; set; }

		[JsonProperty("addState")]
		public string[] AddState { get; set; }

		[JsonProperty("sfx")]
		public object Sfx { get; set; }

		[JsonProperty("fly")]
		public double? Fly { get; set; }

		[JsonProperty("CRIT_PROB")]
		public double? CRITPROB { get; set; }

		[JsonProperty("shaking")]
		public bool? Shaking { get; set; }

		[JsonProperty("move.speed")]
		public double? MoveSpeed { get; set; }

		[JsonProperty("force.ground")]
		public bool? ForceGround { get; set; }

		[JsonProperty("move.speed.prjc")]
		public int? MoveSpeedPrjc { get; set; }

		[JsonProperty("CRIT_DMG")]
		public double? CRITDMG { get; set; }

		[JsonProperty("vamp")]
		public double? Vamp { get; set; }

		[JsonProperty("vfx")]
		public object Vfx { get; set; }

		[JsonProperty("pull")]
		public double? Pull { get; set; }

		[JsonProperty("hit.effect")]
		public string HitEffect { get; set; }

		[JsonProperty("heal.type")]
		public string HealType { get; set; }

		[JsonProperty("pos.target.front.x")]
		public object PosTargetFrontX { get; set; }

		[JsonProperty("pos.target.front.y")]
		public double? PosTargetFrontY { get; set; }

		[JsonProperty("heal.value")]
		public object HealValue { get; set; }

		[JsonProperty("target.iff")]
		public string TargetIff { get; set; }

		[JsonProperty("target.method")]
		public string TargetMethod { get; set; }

		[JsonProperty("repeat.count")]
		public object RepeatCount { get; set; }

		[JsonProperty("repeat.interval")]
		public double? RepeatInterval { get; set; }

		[JsonProperty("damage.type")]
		public string DamageType { get; set; }

		[JsonProperty("on.destroy")]
		public string[] OnDestroy { get; set; }

		[JsonProperty("fire.degree")]
		public object FireDegree { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }

		[JsonProperty("pos.reach.degree")]
		public object PosReachDegree { get; set; }

		[JsonProperty("reach.offset.x")]
		public object ReachOffsetX { get; set; }

		[JsonProperty("reach.pos")]
		public string ReachPos { get; set; }

		[JsonProperty("on.hit.prob")]
		public double? OnHitProb { get; set; }

		[JsonProperty("pos.param")]
		public string PosParam { get; set; }

		[JsonProperty("poolNum")]
		public int? PoolNum { get; set; }

		[JsonProperty("stun")]
		public int? Stun { get; set; }

		[JsonProperty("pos.jump.x")]
		public int? PosJumpX { get; set; }

		[JsonProperty("pos.jump.y")]
		public double? PosJumpY { get; set; }

		[JsonProperty("PENETRATE_DEF")]
		public int? PENETRATEDEF { get; set; }

		[JsonProperty("offset.x")]
		public object OffsetX { get; set; }

		[JsonProperty("offset.y")]
		public double? OffsetY { get; set; }

		[JsonProperty("PENETRATE_RST")]
		public int? PENETRATERST { get; set; }
	}

	public class SkillMaxHandler
	{

		[JsonProperty("codehandler")]
		public string Codehandler { get; set; }

		[JsonProperty("props")]
		public Props3 Props { get; set; }

		[JsonProperty("run.ani_event")]
		public int[] RunAniEvent { get; set; }

		[JsonProperty("run.timing")]
		public double? RunTiming { get; set; }

		[JsonProperty("label")]
		public string Label { get; set; }

		[JsonProperty("run.wait")]
		public string RunWait { get; set; }
	}

	public class Props4
	{

		[JsonProperty("lifetime")]
		public double Lifetime { get; set; }

		[JsonProperty("addState")]
		public string[] AddState { get; set; }

		[JsonProperty("projectile")]
		public string Projectile { get; set; }

		[JsonProperty("damage.type")]
		public string DamageType { get; set; }

		[JsonProperty("damage.value")]
		public object DamageValue { get; set; }

		[JsonProperty("pos.unit.front.x")]
		public double? PosUnitFrontX { get; set; }

		[JsonProperty("push")]
		public double? Push { get; set; }

		[JsonProperty("stun")]
		public object Stun { get; set; }

		[JsonProperty("sfx")]
		public object Sfx { get; set; }

		[JsonProperty("force.ground")]
		public bool? ForceGround { get; set; }

		[JsonProperty("on.destroy")]
		public string[] OnDestroy { get; set; }

		[JsonProperty("move.speed")]
		public int? MoveSpeed { get; set; }

		[JsonProperty("vfx")]
		public object Vfx { get; set; }

		[JsonProperty("pull")]
		public double? Pull { get; set; }

		[JsonProperty("fly")]
		public double? Fly { get; set; }

		[JsonProperty("shaking")]
		public bool? Shaking { get; set; }

		[JsonProperty("repeat.count")]
		public int? RepeatCount { get; set; }

		[JsonProperty("pos.target.front.x")]
		public object PosTargetFrontX { get; set; }

		[JsonProperty("pos.target.front.y")]
		public int? PosTargetFrontY { get; set; }

		[JsonProperty("repeat.interval")]
		public double? RepeatInterval { get; set; }

		[JsonProperty("target.method")]
		public string TargetMethod { get; set; }

		[JsonProperty("fire.speed")]
		public object FireSpeed { get; set; }

		[JsonProperty("fire.degree")]
		public object FireDegree { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }

		[JsonProperty("pos.unit.front.y")]
		public double? PosUnitFrontY { get; set; }
	}

	public class HandlerBasic
	{

		[JsonProperty("codehandler")]
		public string Codehandler { get; set; }

		[JsonProperty("props")]
		public Props4 Props { get; set; }

		[JsonProperty("run.ani_event")]
		public int[] RunAniEvent { get; set; }

		[JsonProperty("run.timing")]
		public double? RunTiming { get; set; }

		[JsonProperty("label")]
		public string Label { get; set; }

		[JsonProperty("run.wait")]
		public string RunWait { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }
	}

	public class Props5
	{

		[JsonProperty("lifetime")]
		public double Lifetime { get; set; }

		[JsonProperty("addState")]
		public string[] AddState { get; set; }

		[JsonProperty("projectile")]
		public string Projectile { get; set; }

		[JsonProperty("damage.type")]
		public string DamageType { get; set; }

		[JsonProperty("damage.value")]
		public object DamageValue { get; set; }

		[JsonProperty("pos.unit.front.x")]
		public double? PosUnitFrontX { get; set; }

		[JsonProperty("push")]
		public double? Push { get; set; }

		[JsonProperty("stun")]
		public double? Stun { get; set; }

		[JsonProperty("move.speed")]
		public int? MoveSpeed { get; set; }

		[JsonProperty("sfx")]
		public object Sfx { get; set; }

		[JsonProperty("force.ground")]
		public bool? ForceGround { get; set; }

		[JsonProperty("on.destroy")]
		public string[] OnDestroy { get; set; }

		[JsonProperty("shaking")]
		public bool? Shaking { get; set; }

		[JsonProperty("vfx")]
		public object Vfx { get; set; }

		[JsonProperty("pos.unit.front.y")]
		public int? PosUnitFrontY { get; set; }

		[JsonProperty("pull")]
		public double? Pull { get; set; }

		[JsonProperty("fly")]
		public double? Fly { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }

		[JsonProperty("on.hit.prob")]
		public double? OnHitProb { get; set; }

		[JsonProperty("pos.target.front.x")]
		public object PosTargetFrontX { get; set; }

		[JsonProperty("target.method")]
		public string TargetMethod { get; set; }

		[JsonProperty("fire.speed")]
		public string FireSpeed { get; set; }

		[JsonProperty("repeat.count")]
		public int? RepeatCount { get; set; }

		[JsonProperty("repeat.interval")]
		public double? RepeatInterval { get; set; }

		[JsonProperty("heal.type")]
		public string HealType { get; set; }

		[JsonProperty("pos.target.front.y")]
		public int? PosTargetFrontY { get; set; }

		[JsonProperty("heal.value")]
		public int? HealValue { get; set; }

		[JsonProperty("target.iff")]
		public string TargetIff { get; set; }
	}

	public class HandlerMax
	{

		[JsonProperty("codehandler")]
		public string Codehandler { get; set; }

		[JsonProperty("props")]
		public Props5 Props { get; set; }

		[JsonProperty("run.ani_event")]
		public object RunAniEvent { get; set; }

		[JsonProperty("run.timing")]
		public double? RunTiming { get; set; }

		[JsonProperty("label")]
		public string Label { get; set; }

		[JsonProperty("run.wait")]
		public string RunWait { get; set; }
	}

	public class Props6
	{

		[JsonProperty("lifetime")]
		public double Lifetime { get; set; }

		[JsonProperty("addState")]
		public string[] AddState { get; set; }

		[JsonProperty("projectile")]
		public string Projectile { get; set; }

		[JsonProperty("damage.type")]
		public string DamageType { get; set; }

		[JsonProperty("damage.value")]
		public object DamageValue { get; set; }

		[JsonProperty("pos.unit.front.x")]
		public double? PosUnitFrontX { get; set; }

		[JsonProperty("push")]
		public double? Push { get; set; }

		[JsonProperty("stun")]
		public object Stun { get; set; }

		[JsonProperty("sfx")]
		public object Sfx { get; set; }

		[JsonProperty("force.ground")]
		public bool? ForceGround { get; set; }

		[JsonProperty("on.destroy")]
		public string[] OnDestroy { get; set; }

		[JsonProperty("move.speed")]
		public int? MoveSpeed { get; set; }

		[JsonProperty("vfx")]
		public object Vfx { get; set; }

		[JsonProperty("pull")]
		public double? Pull { get; set; }

		[JsonProperty("fly")]
		public double? Fly { get; set; }

		[JsonProperty("shaking")]
		public bool? Shaking { get; set; }

		[JsonProperty("pos.target.front.x")]
		public object PosTargetFrontX { get; set; }

		[JsonProperty("target.method")]
		public string TargetMethod { get; set; }

		[JsonProperty("fire.speed")]
		public object FireSpeed { get; set; }

		[JsonProperty("repeat.count")]
		public int? RepeatCount { get; set; }

		[JsonProperty("repeat.interval")]
		public double? RepeatInterval { get; set; }

		[JsonProperty("fire.degree")]
		public object FireDegree { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }

		[JsonProperty("pos.unit.front.y")]
		public double? PosUnitFrontY { get; set; }

		[JsonProperty("pullNum")]
		public int? PullNum { get; set; }

		[JsonProperty("VAMP")]
		public double? VAMP { get; set; }
	}

	public class HandlerMiddle
	{

		[JsonProperty("codehandler")]
		public string Codehandler { get; set; }

		[JsonProperty("props")]
		public Props6 Props { get; set; }

		[JsonProperty("run.ani_event")]
		public int[] RunAniEvent { get; set; }

		[JsonProperty("run.timing")]
		public double? RunTiming { get; set; }

		[JsonProperty("label")]
		public string Label { get; set; }

		[JsonProperty("run.wait")]
		public string RunWait { get; set; }

		[JsonProperty("on.hit")]
		public string[] OnHit { get; set; }
	}

	public class Skillhandlerjson
	{

		[JsonProperty("skillSecondHandlers")]
		public SkillSecondHandler[] SkillSecondHandlers { get; set; }

		[JsonProperty("skillHandlers")]
		public SkillHandler[] SkillHandlers { get; set; }

		[JsonProperty("skillMaxHandlers")]
		public SkillMaxHandler[] SkillMaxHandlers { get; set; }

		[JsonProperty("handler.basic")]
		public HandlerBasic[] HandlerBasic { get; set; }

		[JsonProperty("handler.max")]
		public HandlerMax[] HandlerMax { get; set; }

		[JsonProperty("handler.middle")]
		public HandlerMiddle[] HandlerMiddle { get; set; }
	}

	public class SkillDef
	{

		[JsonProperty("ani")]
		public object Ani { get; set; }

		[JsonProperty("skillicon")]
		public string Skillicon { get; set; }

		[JsonProperty("anidurationlimitsec")]
		public double Anidurationlimitsec { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("desc")]
		public string Desc { get; set; }

		[JsonProperty("passivetype")]
		public string Passivetype { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("range")]
		public object Range { get; set; }

		[JsonProperty("skillhandlerjson")]
		public Skillhandlerjson Skillhandlerjson { get; set; }

		[JsonProperty("subdesc")]
		public string Subdesc { get; set; }

		[JsonProperty("type")]
		public string Type { get; set; }
	}

	public class SkillBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("skill")]
		public SkillDef[] Skill { get; set; }
	}

}
