// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class DropableBreadType
	{

		[JsonProperty("min_grade")]
		public int MinGrade { get; set; }

		[JsonProperty("max_grade")]
		public int MaxGrade { get; set; }
	}

	public class GradeCondition
	{

		[JsonProperty("type")]
		public string Type { get; set; }

		[JsonProperty("value")]
		public int Value { get; set; }
	}

	public class Restrictcondition
	{

		[JsonProperty("class_condition")]
		public string[] ClassCondition { get; set; }

		[JsonProperty("grade_condition")]
		public GradeCondition[] GradeCondition { get; set; }
	}

	public class DropableWeaponType
	{

		[JsonProperty("min_grade")]
		public int MinGrade { get; set; }

		[JsonProperty("max_grade")]
		public int MaxGrade { get; set; }

		[JsonProperty("classids")]
		public string[] Classids { get; set; }
	}

	public class Stage
	{

		[JsonProperty("dropable_bread_type")]
		public DropableBreadType DropableBreadType { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("firstclearrewardvalue")]
		public int Firstclearrewardvalue { get; set; }

		[JsonProperty("clearrewardtype")]
		public string Clearrewardtype { get; set; }

		[JsonProperty("chapter_id")]
		public string ChapterId { get; set; }

		[JsonProperty("heartneed")]
		public int Heartneed { get; set; }

		[JsonProperty("require_atk")]
		public double RequireAtk { get; set; }

		[JsonProperty("restrictcondition")]
		public Restrictcondition Restrictcondition { get; set; }

		[JsonProperty("weaponbox_skin")]
		public string WeaponboxSkin { get; set; }

		[JsonProperty("priority")]
		public int Priority { get; set; }

		[JsonProperty("theme")]
		public string Theme { get; set; }

		[JsonProperty("gypsiappear")]
		public double Gypsiappear { get; set; }

		[JsonProperty("rule")]
		public string Rule { get; set; }

		[JsonProperty("clearrewardvalue")]
		public int Clearrewardvalue { get; set; }

		[JsonProperty("firstclearrewardtype")]
		public string Firstclearrewardtype { get; set; }

		[JsonProperty("require_hp")]
		public double RequireHp { get; set; }

		[JsonProperty("bosses")]
		public object Bosses { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("dropable_weapon_type")]
		public DropableWeaponType DropableWeaponType { get; set; }
	}

	public class StageBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("stage")]
		public Stage[] Stage { get; set; }
	}

}
