// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class Weapon
	{

		[JsonProperty("rarity")]
		public string Rarity { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("grade")]
		public int Grade { get; set; }

		[JsonProperty("range")]
		public double Range { get; set; }

		[JsonProperty("convert_slot_2")]
		public string ConvertSlot2 { get; set; }

		[JsonProperty("categoryid")]
		public string Categoryid { get; set; }

		[JsonProperty("attspd")]
		public double Attspd { get; set; }

		[JsonProperty("convert_slot_3")]
		public string ConvertSlot3 { get; set; }

		[JsonProperty("skin_tex")]
		public string SkinTex { get; set; }

		[JsonProperty("convert_slot_1")]
		public string ConvertSlot1 { get; set; }

		[JsonProperty("attdmg")]
		public int Attdmg { get; set; }

		[JsonProperty("upgradetargetweapon")]
		public string Upgradetargetweapon { get; set; }

		[JsonProperty("face_tex")]
		public string FaceTex { get; set; }

		[JsonProperty("reqhero")]
		public string[] Reqhero { get; set; }

		[JsonProperty("type")]
		public string Type { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("desc")]
		public string Desc { get; set; }
	}

	public class WeaponBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon")]
		public Weapon[] Weapon { get; set; }
	}

}
