// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class WeaponConvertList
	{

		[JsonProperty("huge")]
		public double Huge { get; set; }

		[JsonProperty("convert_value_max")]
		public double ConvertValueMax { get; set; }

		[JsonProperty("dsp_format")]
		public string DspFormat { get; set; }

		[JsonProperty("convert_type")]
		public string ConvertType { get; set; }

		[JsonProperty("convert_target")]
		public string ConvertTarget { get; set; }

		[JsonProperty("unlock_cond")]
		public int UnlockCond { get; set; }

		[JsonProperty("convert_value_min")]
		public double ConvertValueMin { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("list_format")]
		public string ListFormat { get; set; }
	}

	public class WeaponConvertListBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon_convert_list")]
		public WeaponConvertList[] WeaponConvertList { get; set; }
	}

}
