// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{
	public class WeaponConvertCost
	{

		[JsonProperty("grade")]
		public int Grade { get; set; }

		[JsonProperty("required_gold_max")]
		public int RequiredGoldMax { get; set; }

		[JsonProperty("required_gold_init")]
		public int RequiredGoldInit { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("required_gold_incr")]
		public int RequiredGoldIncr { get; set; }
	}

	public class WeaponConvertCostBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon_convert_cost")]
		public WeaponConvertCost[] WeaponConvertCost { get; set; }
	}
}
