// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class WeaponDismantleProp
	{

		[JsonProperty("rewardiron")]
		public int Rewardiron { get; set; }

		[JsonProperty("reward_crystal_prob")]
		public double RewardCrystalProb { get; set; }

		[JsonProperty("grade")]
		public int Grade { get; set; }

		[JsonProperty("reward_piece_prob")]
		public double RewardPieceProb { get; set; }

		[JsonProperty("reward_powder_prob")]
		public double RewardPowderProb { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }
	}

	public class WeaponDismantlePropBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon_dismantle_props")]
		public WeaponDismantleProp[] WeaponDismantleProps { get; set; }
	}

}
