// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class WeaponSellCost
	{

		[JsonProperty("grade")]
		public int Grade { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("goldcost")]
		public int Goldcost { get; set; }
	}

	public class WeaponSellCostBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon_sell_cost")]
		public WeaponSellCost[] WeaponSellCost { get; set; }
	}

}
