// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class WeaponCategory
	{

		[JsonProperty("presentflagimg")]
		public string Presentflagimg { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("fbx")]
		public string Fbx { get; set; }

		[JsonProperty("skillmotionlist")]
		public string[] Skillmotionlist { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("desc")]
		public string Desc { get; set; }
	}

	public class WeaponCategoryBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weaponcategory")]
		public WeaponCategory[] WeaponCategory { get; set; }
	}

}
