// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class ConvertTarget
	{

		[JsonProperty("Target.id")]
		public string TargetId { get; set; }

		[JsonProperty("ChangeType")]
		public string ChangeType { get; set; }

		[JsonProperty("Target.object")]
		public string TargetObject { get; set; }

		[JsonProperty("Target.exName")]
		public string TargetExName { get; set; }

		[JsonProperty("Target.changeName")]
		public string TargetChangeName { get; set; }
	}

	public class WeaponConvertExclusiveOption
	{

		[JsonProperty("reqheroname")]
		public string Reqheroname { get; set; }

		[JsonProperty("convert_type")]
		public string ConvertType { get; set; }

		[JsonProperty("weapon_id")]
		public string WeaponId { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("dsp_format")]
		public string DspFormat { get; set; }

		[JsonProperty("convert_target")]
		public ConvertTarget[] ConvertTarget { get; set; }
	}

	public class WeaponConvertExclusiveOptionBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon_convert_exclusive_option")]
		public WeaponConvertExclusiveOption[] WeaponConvertExclusiveOption { get; set; }
	}

}
