// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IcyBot
{

	public class WeaponGradeupCost
	{

		[JsonProperty("reqpowder")]
		public int Reqpowder { get; set; }

		[JsonProperty("reqiron")]
		public int Reqiron { get; set; }

		[JsonProperty("reqpiece")]
		public int Reqpiece { get; set; }

		[JsonProperty("grade")]
		public int Grade { get; set; }

		[JsonProperty("reqcrystal")]
		public int Reqcrystal { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("reqgold")]
		public int Reqgold { get; set; }

		[JsonProperty("rarity")]
		public string Rarity { get; set; }
	}

	public class WeaponGradeupCostBase
	{

		[JsonProperty("status")]
		public string Status { get; set; }

		[JsonProperty("weapon_gradeup_cost")]
		public WeaponGradeupCost[] WeaponGradeupCost { get; set; }
	}

}
